In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# 데이터 입력

grape = np.array([[19, 300, 0], [20,500,0], [18,400,0], [25,500,1],[27,700,1], [28, 600,1]])

In [3]:
# 분류 알고리즘 2종

from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

In [7]:
# 데이터 전처리

X = grape[:, :2] # 전체 행 중 0~1열
y = grape[:, 2]

print(X, y)

[[ 19 300]
 [ 20 500]
 [ 18 400]
 [ 25 500]
 [ 27 700]
 [ 28 600]] [0 0 0 1 1 1]


In [8]:
# knn 모델 생성

knn = KNeighborsClassifier()

In [10]:
# knn 모델 학습

knn.fit(X, y)

KNeighborsClassifier()

In [11]:
# knn 모델 정확도 확인

knn.score(X, y)

1.0

In [15]:
# Logistic Regression 모델 생성, 학습, 정확도 확인을 해보세요

lr = LogisticRegression()
lr.fit(X, y)
lr.score(X, y)

1.0

In [16]:
# coef: 기울기 / intercept: 절편

print(lr.coef_, lr.intercept_)

[[0.71665314 0.04838074]] [-40.31573036]


In [22]:
# 예측도 해보자

print(lr.predict(X))
print(knn.predict(X))

[0 0 0 1 1 1]
[0 0 0 1 1 1]


In [28]:
print(f"knn은 {'거봉' if knn.predict([[22, 600]]) == 1 else '포도'}")
print(f"lr는 {'거봉' if lr.predict([[22, 600]]) == 1 else '포도'}")
print(f"knn은 {'거봉' if knn.predict([[20, 500]]) == 1 else '포도'}")
print(f"lr는 {'거봉' if lr.predict([[20, 500]]) == 1 else '포도'}")

knn은 거봉
lr는 거봉
knn은 포도
lr는 포도


In [ ]:
size = float(input("포도 한 알의 크기는 (mm): "))
weight = float(input("포도 한 송이의 크기는 (g): "))
result = knn.predict([[size, weight]])
'거봉' if knn.predict([[22, 600]]) == 1 else '포도'}
